"use client";

import { useEffect, useRef, useState } from "react";

interface TourStep {
  /** Matches a real element's `data-tour` attribute elsewhere in the app —
   * this component never renders its own stand-in UI, it only points at
   * what's already on the page. */
  target: string;
  title: string;
  body: string;
  demoOnly?: boolean;
}

const TOUR_STEPS: TourStep[] = [
  {
    target: "freshness",
    title: "Freshness indicator",
    body: "Shows how current the data is — LIVE, RECENT, DELAYED, STALE, or UNAVAILABLE — based on real elapsed time since the last successful fetch, not a fixed timer.",
  },
  {
    target: "brief",
    title: "Today's Brief",
    body: "A short summary of everything currently unacknowledged. It's generated by a deterministic template from the same data as the list below — no LLM in the loop.",
  },
  {
    target: "row-severity",
    title: "Unusualness score",
    body: "2.2σ means today's move is 2.2 standard deviations from this stock's own recent behavior — not a flat percentage rule. The badge translates that number into Notable, Significant, or Extreme.",
  },
  {
    target: "show-evidence",
    title: "Show evidence",
    body: "Opens the full calculation behind a flag — the historical distribution, the exact z-score formula, and this stock's other recent signals — so every flag is auditable, not a black box.",
  },
  {
    target: "watchlist",
    title: "Watchlist",
    body: "Add or remove stocks here. The digest and freshness indicator always reflect exactly what's tracked in this list.",
  },
  {
    target: "demo-controls",
    title: "Demo controls",
    body: "Simulates real feed degradation — outage or staleness — so you can see how freshness and flags behave under actual failure conditions, not just the happy path.",
    demoOnly: true,
  },
];

/** Sequential guided walkthrough — manually triggered ONLY (see AppHeader's
 * "Take a tour" button). Never auto-launches: no mount-time effect checks
 * localStorage or first-visit state, and this component renders nothing
 * unless `open` is true. That's deliberate, not an oversight — the primary
 * use case for this product is a live, presenter-controlled demo, where an
 * overlay appearing unprompted mid-presentation would be actively harmful.
 *
 * Points at real, already-rendered elements via `data-tour` attributes
 * (FreshnessBanner, DigestBrief, DigestRow, WatchlistManager, DemoControls)
 * rather than cloning or rebuilding them — this component only wraps/
 * highlights, it never changes what those elements do.
 *
 * The dimming mechanic reuses the exact `ink/30` backdrop token every other
 * dialog in this app already uses (Dialog.tsx, EvidencePanel.tsx) — applied
 * via a box-shadow spread on the highlight box instead of a flat full-page
 * div, which is what makes the target itself appear undimmed relative to
 * everything else. Same token, no new dimming mechanism.
 *
 * No persisted dismissal state, on purpose: every trigger starts fresh at
 * step 1 (PRODUCT.md/deployment prep don't have a real multi-session user
 * to accommodate here, and the non-negotiable constraint above already
 * rules out anything localStorage-driven near this component). */
export function ProductTour({
  open,
  onClose,
  demoMode,
}: {
  open: boolean;
  onClose: () => void;
  demoMode: boolean;
}) {
  const steps = open ? TOUR_STEPS.filter((s) => !s.demoOnly || demoMode) : [];
  const [stepIndex, setStepIndex] = useState(0);
  const [rect, setRect] = useState<DOMRect | null>(null);
  const dialogRef = useRef<HTMLDivElement>(null);
  const previouslyFocused = useRef<HTMLElement | null>(null);

  useEffect(() => {
    if (open) setStepIndex(0);
  }, [open]);

  const step = steps[stepIndex] as TourStep | undefined;

  // Re-measure the target's position on every step change and on
  // resize/scroll, so the highlight tracks the real element rather than a
  // stale snapshot of where it used to be.
  useEffect(() => {
    if (!open || !step) return;
    function measure() {
      const el = document.querySelector<HTMLElement>(`[data-tour="${step!.target}"]`);
      setRect(el ? el.getBoundingClientRect() : null);
    }
    measure();
    window.addEventListener("resize", measure);
    window.addEventListener("scroll", measure, true);
    return () => {
      window.removeEventListener("resize", measure);
      window.removeEventListener("scroll", measure, true);
    };
  }, [open, step]);

  useEffect(() => {
    if (!open) return;
    previouslyFocused.current = document.activeElement as HTMLElement | null;
    dialogRef.current?.focus();

    function onKeyDown(e: KeyboardEvent) {
      if (e.key === "Escape") {
        onClose();
      } else if (e.key === "ArrowRight") {
        e.preventDefault();
        goNext();
      } else if (e.key === "ArrowLeft") {
        e.preventDefault();
        goBack();
      }
    }
    document.addEventListener("keydown", onKeyDown);
    return () => {
      document.removeEventListener("keydown", onKeyDown);
      previouslyFocused.current?.focus?.();
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [open, stepIndex, steps.length]);

  if (!open || !step) return null;

  function goNext() {
    setStepIndex((i) => (i >= steps.length - 1 ? i : i + 1));
    if (stepIndex >= steps.length - 1) onClose();
  }
  function goBack() {
    setStepIndex((i) => Math.max(0, i - 1));
  }

  const isLast = stepIndex === steps.length - 1;

  // Tooltip placement: below the target when there's room, else above it,
  // else centered — clamped to stay on-screen. Simple by design; this isn't
  // a general-purpose positioning library.
  const TOOLTIP_WIDTH = 320;
  const GAP = 12;
  let tooltipStyle: React.CSSProperties;
  if (rect) {
    const spaceBelow = window.innerHeight - rect.bottom;
    const top = spaceBelow > 160 ? rect.bottom + GAP : Math.max(GAP, rect.top - 160 - GAP);
    const left = Math.min(
      Math.max(GAP, rect.left + rect.width / 2 - TOOLTIP_WIDTH / 2),
      window.innerWidth - TOOLTIP_WIDTH - GAP
    );
    tooltipStyle = { top, left, width: TOOLTIP_WIDTH };
  } else {
    tooltipStyle = {
      top: "50%",
      left: "50%",
      width: TOOLTIP_WIDTH,
      transform: "translate(-50%, -50%)",
    };
  }

  return (
    <>
      {/* Invisible click-catcher — blocks interaction with the real page
          while the tour is open (same layering role as Dialog.tsx's
          backdrop), clicking it skips/closes exactly like clicking a
          dialog's backdrop does elsewhere in this app. */}
      <div className="fixed inset-0 z-40" onClick={onClose} aria-hidden="true" />

      {rect && (
        <div
          aria-hidden="true"
          className="pointer-events-none fixed z-40 rounded-lg ring-2 ring-cobalt transition-[top,left,width,height] duration-200 motion-reduce:transition-none"
          style={{
            top: rect.top - 6,
            left: rect.left - 6,
            width: rect.width + 12,
            height: rect.height + 12,
            // Same ink/30 token used by every other dialog's backdrop in
            // this app (Dialog.tsx, EvidencePanel.tsx) — reused here via
            // box-shadow spread so it dims everything except this box,
            // instead of a flat full-page tint.
            boxShadow: "0 0 0 9999px oklch(0.21 0.024 258 / 0.3)",
          }}
        />
      )}

      <div
        ref={dialogRef}
        role="dialog"
        aria-modal="true"
        aria-labelledby="tour-step-title"
        tabIndex={-1}
        className="animate-panel-in fixed z-50 flex flex-col gap-3 rounded-lg border border-border-strong bg-surface-raised p-4 shadow-[0_12px_32px_-4px_rgba(15,23,42,0.06),0_4px_8px_-2px_rgba(15,23,42,0.03)] focus:outline-none"
        style={tooltipStyle}
      >
        <div className="flex items-center justify-between gap-3">
          <p className="eyebrow">
            {stepIndex + 1} of {steps.length}
          </p>
          <button
            onClick={onClose}
            className="focus-ring rounded text-xs font-medium text-ink-muted transition-colors hover:text-ink"
          >
            Skip
          </button>
        </div>
        <h2 id="tour-step-title" className="text-sm font-semibold text-ink">
          {step.title}
        </h2>
        <p className="text-sm leading-relaxed text-ink-muted">{step.body}</p>
        <div className="mt-1 flex items-center justify-end gap-2">
          <button
            onClick={goBack}
            disabled={stepIndex === 0}
            className="focus-ring rounded-md px-3 py-1.5 text-xs font-medium text-ink-muted transition-colors hover:bg-surface-subtle hover:text-ink disabled:cursor-not-allowed disabled:opacity-40"
          >
            Back
          </button>
          <button
            onClick={goNext}
            className="focus-ring rounded-md bg-cobalt px-3 py-1.5 text-xs font-medium text-white transition-opacity hover:opacity-90"
          >
            {isLast ? "Done" : "Next"}
          </button>
        </div>
      </div>
    </>
  );
}
